main:in_merge.o driver.o lexical.o sl_annotate.o sl_float.o \
	 sl_identifier.o sl_integer.o sl_merge.o sl_number.o sl_operator.o \
	sl_sb.o sl_string.o sl_ws.o 
	gcc -o merge2 in_merge.o driver.o lexical.o sl_annotate.o sl_float.o \
	sl_identifier.o sl_integer.o sl_merge.o sl_number.o sl_operator.o \
	sl_sb.o sl_string.o sl_ws.o 

rm:
	rm -f *.o merge2
